@rootUrl=https://localhost:7268/api/products

###
GET {{rootUrl}}

###
POST {{rootUrl}}
Content-Type: application/json

{
  "name": "New Product2",
  "description": "Description of new product",
  "categoryId": "",
  "price": 99.99
}